[package]
name = "perf-bench"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "bench_aos"
path = "src/bin/bench_aos.rs"

[[bin]]
name = "bench_soa"
path = "src/bin/bench_soa.rs"

[dependencies]
