[package]
name = "common"
version = "0.1.0"
edition = "2024"
description = "Core utilities for for arb-solver"
license = "MIT OR Apache-2.0"
publish = false  # This is a workspace crate, not meant for publishing yet

[dependencies]
